export const workspaceRoutes = {
  home: '/zzz',
  gacha: '/zzz/gacha',
  guides: '/zzz/guides',
  development: {
    overview: '/zzz/development',
    characters: '/zzz/development/characters',
    wEngines: '/zzz/development/w-engines',
    driveDiscs: '/zzz/development/drive-discs',
    materials: '/zzz/development/materials',
    teams: '/zzz/development/teams',
    calculator: '/zzz/development/calculator',
  },
  data: {
    overview: '/zzz/data',
    gacha: '/zzz/data/gacha',
    characters: '/zzz/data/characters',
    wEngines: '/zzz/data/w-engines',
    versions: '/zzz/data/versions',
  },
  encyclopedia: {
    overview: '/zzz/encyclopedia',
    characters: '/zzz/encyclopedia/characters',
    wEngines: '/zzz/encyclopedia/w-engines',
    driveDiscs: '/zzz/encyclopedia/drive-discs',
    monsters: '/zzz/encyclopedia?tab=monsters',
    bosses: '/zzz/encyclopedia?tab=bosses',
  },
  community: {
    feed: '/zzz/community/feed',
  },
  events: '/zzz/events',
  favorites: '/zzz/favorites',
  search: '/zzz/search',
} as const;
