import { CalendarDays, ChevronLeft, Trophy, UsersRound } from '@game-guide-hub/icons';
import { Banner, Card } from '@game-guide-hub/ui';
import { Link, Navigate, useParams } from 'react-router-dom';
import { agents, events, findRelatedContent, guides, materials } from '../../shared/content';
import { Page } from '../../shared/ui/page';
import { PageTransition } from '../../shared/ui/page-transition';
import { Tag } from '../../shared/ui/tag';

export default function EventDetailPage() {
  const { id } = useParams();
  const event = events.find((item) => item.id === id);
  if (!event) return <Navigate replace to="/zzz/events" />;
  const related = findRelatedContent('event', event.id).slice(0, 8);
  return <PageTransition><Page className="page-surface event-detail-page"><Link to="/zzz/events" className="inline-flex min-h-control items-center gap-compact text-label text-text-secondary hover:text-text-primary"><ChevronLeft size={17} />返回活动中心</Link><Banner className="mt-panel" artwork="/assets/zzz-city.jpg" eyebrow={`${event.type} · ${event.status} · 本地 Mock`} title={event.title} description={event.description ?? event.reward}><Tag>{event.duration}</Tag><Tag>{event.startsAt}</Tag></Banner><div className="mt-layout grid gap-layout xl:grid-cols-[minmax(0,1.4fr)_minmax(18rem,0.6fr)]"><article className="space-y-panel"><Card glass="strong"><p className="text-caption text-content-electric">活动奖励</p><h2 className="mt-control text-title2 font-semibold">{event.reward}</h2><p className="mt-compact text-body text-text-secondary">当前完成进度 {event.progress}% 。内容为本地 Mock 展示，实际奖励与开放信息以游戏内公告为准。</p></Card><Card><h2 className="flex items-center gap-control text-title3 font-semibold"><Trophy size={18} className="text-content-electric" />推荐完成路线</h2><p className="mt-content text-body text-text-secondary">优先完成限时目标与高价值兑换，再把剩余电量投入当前养成缺口。每次版本更新后重新确认活动周期与掉落规则。</p></Card><Card><h2 className="flex items-center gap-control text-title3 font-semibold"><UsersRound size={18} className="text-content-electric" />关联内容</h2><div className="mt-content flex flex-wrap gap-control">{related.map((link) => <Link key={`${link.type}-${link.id}`} to={link.to}><Tag>{link.title}</Tag></Link>)}</div></Card></article><aside className="space-y-panel"><Card glass="light"><h2 className="flex items-center gap-control text-label font-semibold"><CalendarDays size={16} className="text-content-electric" />活动信息</h2><dl className="mt-content space-y-control text-caption"><div className="flex justify-between gap-content"><dt>开放状态</dt><dd>{event.status}</dd></div><div className="flex justify-between gap-content"><dt>开始时间</dt><dd>{event.startsAt}</dd></div><div className="flex justify-between gap-content"><dt>持续时间</dt><dd>{event.duration}</dd></div></dl></Card><RelatedPanel eventId={event.id} /></aside></div></Page></PageTransition>;
}
function RelatedPanel({ eventId }: { readonly eventId: string }) { const event = events.find((item) => item.id === eventId); if (!event) return null; const list = [...(event.agentIds ?? []).map((id) => agents.find((item) => item.id === id)?.name), ...(event.materialIds ?? []).map((id) => materials.find((item) => item.id === id)?.name), ...(event.guideIds ?? []).map((id) => guides.find((item) => item.id === id)?.title)].filter((item): item is string => Boolean(item)); return <Card glass="light"><h2 className="text-label font-semibold">关联角色与资料</h2><div className="mt-content flex flex-wrap gap-control">{list.map((item) => <Tag key={item}>{item}</Tag>)}</div></Card>; }
